version: '3'

services:
  mariadb:
    container_name: mariadb #nom du container
    networks:
    - inception #a quel network il appartient
    build:
    context: requirements/mariadb #ou se trouve son dockerfile
    dockerfile: Dockerfile #nom du dockerfile
    env_file: .env #fichier denvironnement pour les variables
    volumes:
    - mariadb:/var/lib/mysql
    restart: unless-stopped #redemarre tant qu il n est pas stop
    expose: #le port a exposer
    - "3306"

  nginx:
    container_name: nginx
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    depends_on: #ne pas demarrer tant que la dependance n a pas demarrer
    - wordpress
    build:
    context: requirements/nginx
    dockerfile: Dockerfile
    env_file: .env
    ports:
    - "443:443" #on indique le port expose a la machine locale
    restart: on-failure #le conteneur redemarre uniquement en cas de crash

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    build:
    context: requirements/wordpress
    dockerfile: Dockerfile
    depends_on:
    - mariadb
    restart: on-failure
    expose:
    - "9000"